### PR TITLE
shows PSChildPaneSpecifier only

### PR DESCRIPTION
**Pull request by cathandnya**
Remove the top `Licenses` item.

### CODE REVIEW

**Comment by yhirano** [comment]
How does this problem happen?
This problem doesn't seem to happen that using LicensePlist.

**Comment by aki-mizu** [comment]
It happens to me as well.  
"PSGroupSpecifier" has been added to the first of licenses array in this pull request in order to support iOS 13.
https://github.com/mono0926/LicensePlist/pull/109

**Comment by yhirano** [comment]
Thank you @darlhz!
I fix this issue this weekend.

**Comment by yhirano** [comment]
Fixed and released a new version(2.1.1).

**Pull request closed without merging**
